### ISSUE TITLE
Exception message seems to be the wrong way around

### ISSUE THREAD

**Issue by wvanzeist** [Krytic/Takahe#9]
Not really a major issue, just something I noticed while looking at the code: In histogram.py, on line 400, there is an exception with the message "x1 should be larger than x2". But x1 being larger than x2 is what _triggers_ the exception based on the line above, and the docstring says x1 is the lower bound and x2 the upper, so I think the exception message should actually be "x1 should be smaller than x2" or "x2 should be larger than x1".

EDIT (20 Oct): After the latest update, this issue is now on line 357 of histogram.py.

**Comment by Krytic** [comment]
Thanks for bringing this to my attention! I don't know why github didn't send me a notification for this issue :| Simple fix, will push something now :-)
